inherit_gem:
  rubocop-shopify: rubocop.yml

Style/MixinUsage:
  Enabled: true
  Exclude:
    - test/dummy/bin/**/*

Style/ClassVars:
  Enabled: true
  Exclude:
    - lib/slackify/handlers/base.rb

AllCops:
  TargetRubyVersion: 2.6

Gemspec/RequiredRubyVersion:
  Enabled: false
